const juiceData = [
  {
    id: 1,
    color: "Red",
    fruits: ["Apple", "Strawberry"],
    title: "Red Delight",
    description: "A sweet blend of apples and strawberries.",
    price: "$3.99",
    name: "Berry Apple Twist",
    available: false,
  },
  {
    id: 2,
    color: "Green",
    fruits: ["Kiwi", "Lime"],
    title: "Green Zest",
    description: "Tart and refreshing with kiwi and a hint of lime.",
    price: "$4.50",
    name: "Kiwi Lime Fusion",
    available: false,
  },
  {
    id: 3,
    color: "Yellow",
    fruits: ["Pineapple", "Mango"],
    title: "Tropical Sunrise",
    description: "A tropical blend of ripe pineapple and mango.",
    price: "$4.25",
    name: "Mango Pineapple Breeze",
    available: false,
  },
  {
    id: 4,
    color: "Purple",
    fruits: ["Blueberry", "Grape"],
    title: "Purple Potion",
    description: "Rich in antioxidants with blueberries and grapes.",
    price: "$5.00",
    name: "Grape Berry Mix",
    available: false,
  },
  {
    id: 5,
    color: "Orange",
    fruits: ["Orange", "Carrot"],
    title: "Orange Boost",
    description: "Vitamin-rich blend of orange and carrot.",
    price: "$3.75",
    name: "Carrot Citrus Splash",
    available: false,
  },
  {
    id: 6,
    color: "Pink",
    fruits: ["Guava", "Strawberry"],
    title: "Pink Paradise",
    description: "A refreshing mix of guava and strawberries.",
    price: "$4.00",
    name: "Strawberry Guava Blend",
    available: false,
  },
  {
    id: 7,
    color: "Orange",
    fruits: ["Peach", "Orange"],
    title: "Sunset Glow",
    description: "A sweet and tangy blend of peach and orange.",
    price: "$3.99",
    name: "Peach Sunrise",
    available: false,
  },
  {
    id: 8,
    color: "Green",
    fruits: ["Green Apple", "Cucumber"],
    title: "Green Refresh",
    description: "A cool and crisp apple-cucumber mix.",
    price: "$4.20",
    name: "Cucumber Apple Splash",
    available: false,
  },
  {
    id: 9,
    color: "Yellow",
    fruits: ["Lemon", "Ginger"],
    title: "Zesty Lemonade",
    description: "A zingy lemon and ginger blend.",
    price: "$3.80",
    name: "Ginger Lemon Twist",
    available: false,
  },
  {
    id: 10,
    color: "Red",
    fruits: ["Cherry", "Pomegranate"],
    title: "Ruby Red",
    description: "A rich blend of cherry and pomegranate.",
    price: "$4.50",
    name: "Pomegranate Cherry Fusion",
    available: false,
  },

  {
    id: 11,
    color: "Pink",
    fruits: ["Watermelon", "Dragonfruit"],
    title: "Dragon Watermelon Burst",
    description: "Exotic dragonfruit blended with sweet watermelon.",
    price: "$4.75",
    name: "Watermelon Dragon Delight",
    available: false,
  },
  {
    id: 12,
    color: "Green",
    fruits: ["Mint", "Cucumber"],
    title: "Minty Freshness",
    description: "Cool and refreshing mint with a touch of cucumber.",
    price: "$3.50",
    name: "Cucumber Mint Cooler",
    available: false,
  },
  {
    id: 13,
    color: "Red",
    fruits: ["Raspberry", "Beet"],
    title: "Raspberry Beet Fusion",
    description: "A mix of tart raspberry and earthy beet.",
    price: "$4.00",
    name: "Beet Berry Blend",
    available: false,
  },
  {
    id: 14,
    color: "Yellow",
    fruits: ["Banana", "Pineapple"],
    title: "Tropical Yellow",
    description: "Sweet blend of banana and pineapple for a tropical taste.",
    price: "$3.95",
    name: "Banana Pineapple Smoothie",
    available: false,
  },
  {
    id: 15,
    color: "Purple",
    fruits: ["Blackcurrant", "Blueberry"],
    title: "Berry Purple",
    description: "Rich and deep flavors of blackcurrant and blueberry.",
    price: "$4.50",
    name: "Currant Blue Fusion",
    available: false,
  },
  {
    id: 16,
    color: "Orange",
    fruits: ["Pumpkin", "Carrot"],
    title: "Autumn Harvest",
    description: "A hearty blend of pumpkin and carrot, perfect for fall.",
    price: "$4.25",
    name: "Pumpkin Carrot Delight",
    available: false,
  },
  {
    id: 17,
    color: "Green",
    fruits: ["Kale", "Green Apple"],
    title: "Green Detox",
    description: "Healthy kale mixed with sweet green apple.",
    price: "$4.75",
    name: "Kale Apple Cleanse",
    available: false,
  },
  {
    id: 18,
    color: "Red",
    fruits: ["Tomato", "Red Pepper"],
    title: "Savory Red",
    description: "Unique blend of tomato and red pepper for a savory twist.",
    price: "$3.80",
    name: "Tomato Pepper Zing",
    available: false,
  },
  {
    id: 19,
    color: "Yellow",
    fruits: ["Lemon", "Pear"],
    title: "Pear Lemon Delicacy",
    description: "A subtle mix of pear with a hint of lemon.",
    price: "$4.00",
    name: "Lemon Pear Fusion",
    available: false,
  },
  {
    id: 20,
    color: "Purple",
    fruits: ["Grape", "Plum"],
    title: "Purple Sweetness",
    description: "Sweet and rich blend of grapes and plums.",
    price: "$4.50",
    name: "Grape Plum Mix",
    available: false,
  },
  {
    id: 21,
    color: "Green",
    fruits: ["Avocado", "Spinach"],
    title: "Green Power",
    description: "Nutrient-packed blend of avocado and spinach.",
    price: "$5.00",
    name: "Avocado Spinach Boost",
    available: false,
  },
  {
    id: 22,
    color: "Orange",
    fruits: ["Mango", "Carrot"],
    title: "Sunrise Blend",
    description: "A vibrant mix of mango and carrot.",
    price: "$4.20",
    name: "Mango Carrot Smoothie",
    available: false,
  },

  {
    id: 23,
    color: "Yellow-Green",
    fruits: ["Green Apple", "Pear"],
    title: "Orchard Fresh",
    description: "Crisp and refreshing blend of green apple and pear.",
    price: "$3.95",
    name: "Apple Pear Medley",
    available: false,
  },
  {
    id: 24,
    color: "Red",
    fruits: ["Cranberry", "Apple"],
    title: "Cran-Apple Splash",
    description: "Tart cranberry meets sweet apple in this vibrant blend.",
    price: "$4.25",
    name: "Cranberry Apple Fusion",
    available: false,
  },
  {
    id: 25,
    color: "Purple",
    fruits: ["Blackcurrant", "Blueberry"],
    title: "Berry Deep",
    description: "A deep, rich blend of blackcurrant and blueberry.",
    price: "$4.75",
    name: "Currant Berry Delight",
    available: false,
  },
  {
    id: 26,
    color: "Orange",
    fruits: ["Carrot", "Pumpkin"],
    title: "Autumn Harvest",
    description: "A unique blend of carrot and pumpkin for a fall flavor.",
    price: "$3.85",
    name: "Pumpkin Carrot Craze",
    available: false,
  },
  {
    id: 27,
    color: "Pink",
    fruits: ["Watermelon", "Dragonfruit"],
    title: "Dragon Melon Twist",
    description: "Exotic dragonfruit mixed with sweet watermelon.",
    price: "$5.00",
    name: "Melon Dragon Fusion",
    available: false,
  },
  {
    id: 28,
    color: "Green",
    fruits: ["Cucumber", "Mint"],
    title: "Cooling Breeze",
    description: "A refreshing and cooling blend of cucumber and mint.",
    price: "$3.50",
    name: "Minted Cucumber Splash",
    available: false,
  },
  {
    id: 29,
    color: "Red-Orange",
    fruits: ["Blood Orange", "Grapefruit"],
    title: "Citrus Surge",
    description: "A tangy and invigorating mix of blood orange and grapefruit.",
    price: "$4.50",
    name: "Grapefruit Orange Zest",
    available: false,
  },
  {
    id: 30,
    color: "Yellow",
    fruits: ["Pineapple", "Banana"],
    title: "Tropical Smoothie",
    description: "A creamy blend of pineapple and banana for a tropical treat.",
    price: "$4.00",
    name: "Banana Pineapple Swirl",
    available: false,
  },
];
